sudo: required
services:
    - docker
    
before_install:
    - docker build -t alexusarov/docker_react -f dockerfile.dev .
    
script:
    - docker run alexusarov/docker_react npm run test -- --coverage